// The one Prompt Studio build. Desktop loads a single desktop/plugin.js, generated whole from desktop/src/*:
//   plugin-head.js                         the imports and ID (the only file that may import)
//   // @studio-start .. // @studio-end    engine-opus, engine-astra (each in its own scope), i18n-core, studio-core
//   // @ui-i18n-start .. // @ui-i18n-end  desktop/src/i18n-ui.js
//   UI_FILES (below), concatenated verbatim  studio-state.js holds the // @core-start .. // @core-end reducer
// and desktop/studio-core.mjs (same code, with exports) is written for the Node tests.
// `node scripts/build.mjs --check` writes nothing and exits 1 when either output is stale.
import { readFile, writeFile } from 'node:fs/promises'

const url = path => new URL(`../${path}`, import.meta.url)
const read = path => readFile(url(path), 'utf8')
const check = process.argv.includes('--check')

const IMPORT_LINE = /^import\s[^\n]*\n/gm
const stripImports = source => source.replace(IMPORT_LINE, '')
const stripExports = source => source.replace(/^export (?=(const|let|function|class|async function) )/gm, '')

// Top-level declared names (column 0), to prove the inlined code cannot collide with plugin.js.
function topLevelNames(source) {
  const names = new Set()
  for (const m of source.matchAll(/^(?:export )?(?:const|let|var|class|function|async function)\s+([A-Za-z_$][\w$]*)/gm)) names.add(m[1])
  for (const m of source.matchAll(/^import\s*\{([^}]*)\}/gm)) {
    for (const part of m[1].split(',')) {
      const name = part.trim().split(/\s+as\s+/).pop()
      if (name) names.add(name)
    }
  }
  for (const m of source.matchAll(/^import\s+([A-Za-z_$][\w$]*)\s/gm)) names.add(m[1])
  return names
}

// Each engine keeps its private names inside its own function scope; only NAME is exposed.
function engineModule(source, name, file) {
  if (/^import\s/m.test(source)) throw new Error(`${file} must not import anything`)
  return `// ${file}\nconst ${name} = (() => {\n${stripExports(source).trim()}\nreturn ENGINE\n})()`
}

// Hand-written plugin code, in plugin.js order. They share plugin.js's single module scope.
const UI_FILES = ['studio-state.js', 'ui-locale.js', 'ui-prefs.js', 'ui-flow.js', 'ui-components.js']

const [opus, astra, coreI18n, core, uiI18n, head, plugin, oldMjs, ...uiSources] = await Promise.all([
  read('desktop/src/engine-opus.js'), read('desktop/src/engine-astra.js'), read('desktop/src/i18n-core.js'),
  read('desktop/src/studio-core.js'), read('desktop/src/i18n-ui.js'), read('desktop/src/plugin-head.js'),
  read('desktop/plugin.js').catch(() => ''), read('desktop/studio-core.mjs').catch(() => ''),
  ...UI_FILES.map(file => read(`desktop/src/${file}`))
])
UI_FILES.forEach((file, i) => {
  if (/^\s*import\b/m.test(uiSources[i])) throw new Error(`desktop/src/${file} must not import anything (imports live in plugin-head.js)`)
})
const ui = uiSources.join('')

const coreImports = [...core.matchAll(/^import\s[^\n]*from\s+'([^']+)'/gm)].map(m => m[1]).sort()
const allowed = ['./engine-astra.js', './engine-opus.js', './i18n-core.js']
if (JSON.stringify(coreImports) !== JSON.stringify(allowed)) throw new Error(`studio-core.js may import only ${allowed.join(', ')}; found ${coreImports.join(', ')}`)

const header = '// Generated by scripts/build.mjs from desktop/src/*: do not edit here.'
const withExports = [
  header,
  engineModule(opus, 'OPUS_ENGINE', 'desktop/src/engine-opus.js'),
  engineModule(astra, 'ASTRA_ENGINE', 'desktop/src/engine-astra.js'),
  `// desktop/src/i18n-core.js\n${coreI18n.trim()}`,
  `// desktop/src/studio-core.js\n${stripImports(core).trim()}`
].join('\n\n')
const mjs = `${withExports}\n`
const studioBlock = stripExports(withExports)
const uiBlock = `// Copied from desktop/src/i18n-ui.js (the build inlines it; do not edit here).\n${stripExports(uiI18n).trim()}`

// Collision check: names the blocks declare vs every other top-level name in plugin.js.
const rest = `${head}${ui}`
const outside = topLevelNames(rest)
const seen = new Map()
// Engine internals live in their own function scope, so only their exposed names count.
const modules = [['engine-opus.js', 'const OPUS_ENGINE = 0'], ['engine-astra.js', 'const ASTRA_ENGINE = 0'], ['i18n-core.js', coreI18n], ['studio-core.js', stripImports(core)], ['i18n-ui.js', uiI18n]]
for (const [label, source] of modules) {
  for (const name of topLevelNames(source)) {
    if (outside.has(name)) throw new Error(`name collision: ${name} (${label} block) is also declared in plugin.js`)
    if (seen.has(name)) throw new Error(`name collision: ${name} declared by both ${seen.get(name)} and ${label}`)
    seen.set(name, label)
  }
}

const pluginHeader = `// Generated by scripts/build.mjs: do not edit here. Edit desktop/src/plugin-head.js, ${UI_FILES.map(f => `desktop/src/${f}`).join(', ')} (hand-written UI) or the inlined desktop/src/* modules, then run node scripts/build.mjs.\n`
const next = `${pluginHeader}${head}// @studio-start\n${studioBlock}\n// @studio-end\n\n// @ui-i18n-start\n${uiBlock}\n// @ui-i18n-end\n\n${ui}`

if (check) {
  const stale = [next !== plugin && 'desktop/plugin.js', mjs !== oldMjs && 'desktop/studio-core.mjs'].filter(Boolean)
  if (stale.length) {
    console.error(`stale build output: ${stale.join(', ')}. Run: node scripts/build.mjs`)
    process.exit(1)
  }
  console.log('build output is up to date')
} else {
  await writeFile(url('desktop/plugin.js'), next, 'utf8')
  await writeFile(url('desktop/studio-core.mjs'), mjs, 'utf8')
  console.log(`studio block: ${studioBlock.length} chars; ui-i18n block: ${uiBlock.length} chars`)
}
